services:
  web:
    build: .
    command: python3 main.py
    depends_on:
      - mysql
      - storage
    volumes:
      - .:/app
    ports:
      - 8000:8000
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: madsoft
      MYSQL_DATABASE: memes
      MYSQL_USER: madsoft
      MYSQL_PASSWORD: madsoft
  storage:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=madsoft
      - MINIOT_ROOT_PASSWORD=madsoft